
__all__ = ['generate_other_stub']

import textwrap


def generate_other_stub():
    names = [
        'add', 'and_', 'cmp', 'div', 'floordiv', 'if_else', 'inv', 'lshift',
        'mul', 'neg', 'or_', 'pos', 'rshift', 'sub', 'xor',
    ]
    return names, textwrap.dedent(f"""
    def add(a: Any, b: Any, /) -> Any: ...

    def and_(a: Any, b: Any, /) -> Any: ...

    def cmp(a: Any, b: Any, /) -> Any: ...

    def div(a: Any, b: Any, /) -> Any: ...

    def floordiv(a: Any, b: Any, /) -> Any: ...

    def if_else(b: Any, x: Any, y: Any, /) -> Any: ...

    def inv(a: Any, /) -> Any: ...

    def lshift(a: Any, b: Any, /) -> Any: ...

    def mul(a: Any, b: Any, /) -> Any: ...

    def neg(a: Any, /) -> Any: ...

    def or_(a: Any, b: Any, /) -> Any: ...

    def pos(a: Any, /) -> Any: ...

    def rshift(a: Any, b: Any, /) -> Any: ...

    def sub(a: Any, b: Any, /) -> Any: ...

    def xor(a: Any, b: Any, /) -> Any: ...
    """)
